version: 0.1
phases:
  post_build:
    commands:
      - aws s3 sync --delete --exclude img/* . "s3://${BUCKET_NAME}"
      - aws s3 sync --delete --cache-control "max-age=31536000" img "s3://${BUCKET_NAME}/img"
